### ISSUE TITLE
Work arround !

### ISSUE THREAD

**Issue by webdesign7** [sgruhier/jquery-addresspicker#38]
The script is awesome ! but there is a small shortcoming ... 

Let's put this situation.
I have typed an address->selected from suggestion list.Then I want to change the address with another one  -> I start typing the new address -> but for this time instead of selecting an address from list of suggestions I will move the cursor out and in the field box will remain address which I have typed ( not one from suggestion list ) . 
This will conduct to wrong data across the form because the address and the geodata will not match and this could be confusing . 

Solution:

for the mouseout event to be provided a method to check if the result has been selected from the list of suggestions !

if its true that is good if not than something needs to be done  :) 

Please take this in consideration !

Thank you 
Sergiu

**Comment by sgruhier** [comment]
Check out the demo http://xilinus.com/jquery-addresspicker/demos/ and the "Reverse Geocode after Marker Drag?" above the map.

The use case you gave is correct but the use case of selecting a address from suggestion list and move to marker to the correct position because google map geocoder is wrong makes sense too.
